title: JuliaFEM
email: firstname@juliafem.org
description: >
    The JuliaFEM project develops open-source software for reliable,
    scalable, distributed Finite Element Method.
baseurl: ""
url: "http://juliafem.org"
twitter_username: JuliaFEM
github_username:  JuliaFEM

permalink: /:year/:month/:day/:title/

# Discus Comments
disqus:
    shortname: juliafem

# collection for examples
collections:
  examples:
    output: true
    permalink: /:collection/:path

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-postfiles
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - bundler
  - scripts
  - README.md
  - .gitignore
